version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.2
    hostname: zookeeper
    container_name: zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=178.128.85.19
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=9999

  kafka-jmx-exporter:
    image: bitnami/jmx-exporter
    ports:
      - "8080:8080"
    links:
      - kafka
    command:
      - "8080"
      - "/conf/kafka.yml"
    volumes:
      - ./kafka.yml:/conf/kafka.yml

  prometheus:
    ports:
      - 9090:9090/tcp
    image: prom/prometheus:0.18.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - kafka-jmx-exporter

  grafana:
    image: grafana/grafana:3.0.1
    ports:
      - 3000:3000/tcp
    links:
      - prometheus
    volumes:
      - "graf-db:/var/lib/grafana"

  graf-db:
    command:
      - cat
    image: infinityworks/graf-db:08
    links:
      - prometheus
    volumes:
      - "graf-db:/var/lib/grafana/"

volumes:
  graf-db: